name: Deploy to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      # - '*'         # matches every branch that doesn't contain a '/'
      # - '*/*'       # matches every branch containing a single '/'
      # - '**'        # matches every branch
      - main        # Change this to your default branch
  pull_request:
        types: [opened, synchronize, reopened]

jobs:
  
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t static-site .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker tag static-site "${{ secrets.DOCKERHUB_USERNAME }}/static-site:latest" && docker push "${{ secrets.DOCKERHUB_USERNAME }}/static-site:latest"
